const NEXT_PUBLIC_BAG_ID_COOKIE_NAME = 'hobbylobby-cart';
const NEXT_PUBLIC_ANONYMOUS_ID_COOKIE_NAME = 'hl-anon-id';
const NEXT_PUBLIC_JSESSION_ID_COOKIE_NAME = 'JSESSIONID';

const cookieList = [
  NEXT_PUBLIC_BAG_ID_COOKIE_NAME,
  NEXT_PUBLIC_ANONYMOUS_ID_COOKIE_NAME,
  NEXT_PUBLIC_JSESSION_ID_COOKIE_NAME
];

export { cookieList };
